---
- name: Установка конфигов для zabbix-agent
  gather_facts: no
  become: yes
  hosts: all
  vars:
    file: /etc/zabbix/zabbix_agent2.conf
    sziconf: /etc/zabbix/zabbix_agent2.d/szi.conf
    service: zabbix-agent2
    ip: 192.168.34.101

  tasks:
    - name: Получение значения в Server=
      shell: "grep -E '^Server=' {{file}}"
      register: check_server

    - debug:
        var: check_server.stdout
