- name: Установка Drweb
  hosts: all
  become: yes
  gather_facts: no
  vars:
    way: /home/distribution/szi-for-linux/drweb/
    packages:
      work: drweb-workstations_11.1.4-2307031224+fstek-4ud~linux_amd64.run
      file: drweb-file-servers_11.1.4-2307031224+fstek-4ud~linux_amd64.run
    cert: certificate_e0a9c070-56a3-11e9-7191-8444d45ee50b.pem
    ip: '91.230.91.5:2193'
    pack: "{{packages[input] | default('')}}"

  vars_prompt:
    - name: input
      prompt: "Какой пакет установить? workstations / file-servers (work/file)"
      private: no

  tasks:
    - name: Ошибка
      fail:
        msg: "Нужно выбрать пакет"
      when: input not in ['work','file']

    - name: Проверка установлен ли kesl
      shell: "kesl-control --app-info | grep Версия"
      register: kesl
      failed_when: no

    - name: Проверка установлен ли drweb-agent
      shell: "drweb-ctl -v"
      register: check
      failed_when: no

    - debug:
        msg: "{{check.stdout}}{{kesl.stdout.replace(' ','')}}"

    - name: Копирование {{pack}}
      copy:
        src: "{{way}}{{pack}}"
        dest: "/home/{{ansible_user}}/"
      become: no
      when: check.rc != 0 and kesl.rc != 0

    - name: Установка {{pack}}
      shell: "sh /home/{{ansible_user}}/{{pack}} -- -n"
      when: check.rc != 0 and kesl.rc != 0

    - name: Проверка подключения
      shell: "drweb-ctl app | grep -E '^(ConfigD|ESAgent|MeshD|Update)'"
      register: check2
      failed_when: no

    - debug:
        msg: "{{check2.stdout_lines | default('')}}"

    - name: Копирование {{cert}}
      copy:
        src: "{{way}}{{cert}}"
        dest: "/home/{{ansible_user}}/"
      become: no
      when: "'Connected' not in check2.stdout and check2.rc == 0"

    - name: Подключение к серверу {{ip}}
      shell: "drweb-ctl esc {{ip}} --Certificate /home/{{ansible_user}}/{{cert}}"
      register: id_agent
      when: "'Connected' not in check2.stdout and check2.rc == 0"
      failed_when: no

    - debug:
        msg: "{{id_agent.stdout_lines | default('')}}"
