- name: Подключение оркестратору и серверу
  hosts: all
  become: yes
  tasks:

    - name: Убедиться, что Python-библиотека pexpect установлена
      ansible.builtin.yum:
        name: python3-pexpect
        state: present
        
    - name: Выполнение snnetctl -s
      ansible.builtin.command:
        cmd: /opt/securitycode/sns/bin/snnetctl -s
      register: snnetctl_output

    - name: Выполнение snconnctl -s
      ansible.builtin.command:
        cmd: /opt/securitycode/sns/bin/snconnctl -s
      register: snconnctl_output

    - name: Получение имени хоста
      ansible.builtin.set_fact:
        hostname_output: "{{ ansible_hostname }}"

    - name: Объединение всех результатов в одну строку
      ansible.builtin.set_fact:
        result: "{{ hostname_output }},  {{ snnetctl_output.stdout }}, {{ snconnctl_output.stdout }}"

    - name: Печать всех результатов через запятую
      ansible.builtin.debug:
        msg: "{{ result | regex_replace('[\n\r]', ' ') | regex_replace('Введите учетные данные администратора безопасности.*?Настройки успешно сохранены', '') | regex_replace('\\+[-\\+]+\\+', '') | regex_replace('\\|', '') | regex_replace('\\s+', ' ') | regex_replace('Обновление настроек каждые 60 минут|Настройки соединения с сервером Название агента:|Описание агента: IP Адрес: 192.168.131.8 Порт: 443|Настройки соединения с сервером', '') | trim }}"

    - name: Выполнение команды подключения к оркестратору
      expect:
        command: "sudo /opt/securitycode/sns/bin/snconnctl --registration --ip=192.168.131.8"
        responses:
          "логин:": "snsadmin"
          "пароль:": "!28EdjGznVtc"
          "Подключиться к существующему объекту?": "n"
      register: registration_result
      ignore_errors: yes
      when: "'Нет соединения с Security Code Orchestrator' in result"

    - name: удаление записи на оркестраторе (если ошибка записи в бд)
      expect:
        command: "snconnctl -D"
        responses:
          "логин:": "snsadmin"
          "пароль:": "!28EdjGznVtc"
      register: registration_result_deleted
      ignore_errors: yes
      when: "'настройки не сохранены' in registration_result"

    - name: Повторное выполнение команды подключения к оркестратору
      expect:
        command: "sudo /opt/securitycode/sns/bin/snconnctl --registration --ip=192.168.131.8"
        responses:
          "логин:": "snsadmin"
          "пароль:": "!28EdjGznVtc"
      register: registration_result_new
      ignore_errors: yes
      when: "'настройки не сохранены' in registration_result" 

    - name: Проверка
      debug:
        msg: "Хост уже подключен к оркестратору"
      when: "'Агент уже зарегистрирован' in registration_result.stdout"

    - name: Вывод результата подключения
      debug:
        msg: "{{ registration_result_new | registration_result.stdout | regex_replace('[\\n\\r]', ' ') | regex_replace('Введите учетные данные администратора безопасности.*?Настройки успешно сохранены', '') | regex_replace('\\+[-\\+]+\\+', '') | regex_replace('\\|', '') | regex_replace('\\s+', ' ') | trim }}"
      when: "'Агент уже зарегистрирован' not in registration_result.stdout"