---
- name: Запуск команды patchelf от имени root
  hosts: all
  become: true
  become_user: root

  tasks:
    # 1. Получение фактов о пакетах
    - name: Получить факты о пакетах
      ansible.builtin.package_facts:

    # 2. Проверка, установлен ли пакет patchelf
    - name: Проверить, установлен ли patchelf
      ansible.builtin.debug:
        msg: "Пакет patchelf уже установлен"
      when: "'patchelf' in ansible_facts.packages"  # Если пакет уже установлен

    # 3. Установка patchelf, если он не установлен
    - name: Установить patchelf
      ansible.builtin.yum:
        name: patchelf
        state: present
      when: "'patchelf' not in ansible_facts.packages"  # Если пакет не установлен
      register: result
      failed_when: result.rc != 0

    # 4. добавление библиотеки в patchelf
    - name: Добавить нужную библиотеку в бинарник с помощью patchelf
      command: patchelf --remove-needed /lib64/libboost_filesystem.so.1.73.0 /opt/securitycode/sns/lib/libsnldap.so

